@startuml

class Component{
    +isVisible(): boolean
}

class CGovField {

    -theField: WebElement

    +CGovField(field WebElement)
    +setFocus(): void
}
CGovField <|-- Component

class TextField {
    +TextField(field WebElement)

    +enterText(text: string): void
    +hitEnter(): void
}
TextField <|-- CGovField

class CheckBox {
    +CheckBox(field WebElement)

    +click(): void
    +isSelected(): boolean
}
CheckBox <|-- CGovField

class Button {
    +Button(field WebElement)

    click(): void
}
Button <|-- CGovField

class RadioButton {
    +radioButton(field WebElement)

    click(): void
}
RadioButton <|-- CGovField

class AutoSuggestField {
    +AutoSuggestField(field WebElement)

    +selectItem(text: string): void
}
AutoSuggestField <|-- TextField

class Accordian {
    +getTitle() : String
    +getDecription() : BlobOfText
    +isExpanded() : boolean
}
Accordian <|-- Component

class Delighter {
+isIconDisplayed() : boolean
+getLinkTitle() : String
+getLink() : Link

}
Delighter <|-- Component

class ErrorDisplay{
+ErrorDisplay (scope Webelement)

+getMessage() : String
}
ErrorDisplay <|-- Component

class Pager{

+getNumberOfPages() : int

}
Pager <|-- Component

@enduml

