@startuml

class PageObjectBase {

    -browser: WebDriver
    -config: Confguration
    -wait: WebDriverWait

    +PageObjectBase(path: string)
    #PageObjectBase()

    +getPageUrl(): ParsedURL
    +getPageTitle(): string
    +expectUrlChange(IPageChangeAction action): void

    #getBrowser(): WebDriver
}

'' This is actually a public, nested class inside PageObjectBase
interface IPageChangeAction {
    operation(): void
}

package cts {

    '' General cts page functionality (Mainly "is the react app running?")
    class CTSPage {
        isHeaderDisplayed(): boolean
    }
    CTSPage <|-- PageObjectBase

    class cts.BasicSearchPage {
        -age: TextField
        -zipCode: TextField
        -keywordText: AutoSuggestField
        -searchButton: Button
        -zipAlert: Something
        -ageAlert: Something

        +BasicSearchPage(WebElement)

        +getAgeField(): TextField
        +getZipCodeField(): TextField
        +getKeywordField(): AutoSuggestField
        +getSearchButton(): Button
        +getZipAlert(): Something
        +getAgeAlert(): Something

        +hitEnterOnField(field: TextField): cts.SearchNavigationResult
    }
    cts.BasicSearchPage <|-- CTSPage

    class cts.AdvancedSearchPage {
        - cancerTypeSection : CancerTypeSection
        - age : TextField
        - keyword : TextField
        - locationSection : LocationSection
        - trialTypeSection : TrialTypeSection
        - trialPhaseSection : TrialPhaseSection
        - drugTreatmentSection : DrugTreatmentSection
        - trialId : TextField
        - trialInvestigators : Autosuggest
        - leadOrganization : Autosuggest
        - formAction : FormAction

        +getCancerTypeSection(): CancerTypeSection
        +getAgeField(): TextField
        +getKeywordField(): TextField
        +getLocationSection(): LocationSection
        +getTrialTypeSection(): TrialTypeSection
        +getDrugTreatmentSection(): DrugTreatmentSection
        +getTrialPhaseSection(): TrialPhaseSection
        +getTrialID(): TextField
        +getTrialInvestigators(): Autosuggest
        +getLeadOrganization(): Autosuggest
        +getFormAction(): FormAction

    }
    cts.AdvancedSearchPage <|-- CTSPage

    class cts.SearchResultsPage {
        -resultListSection : ResultListSection
        -criteriaSection : CriteriaSection
        -startOverLink : Link
        -modifySearchCriteriaButton : Button
        -selectAllOnPage : CheckBox
        -printSelected : Button
        -pager : Pager

        +getResultListSection(): ResultListSection
        +getCriteriaSection(): CriteriaSection
        +getStartOver(): Link
        +getModifySearchCriteria(): Button
        +getSelectAllOnPage(): CheckBox
        +getPrintSelected(): Button
        +getPager(): Pager


    }
    cts.SearchResultsPage <|-- CTSPage

    class cts.TrialDetailsPage {
        -criteriaSection : CriteriaSection
        -startOverLink : Link
        -trialStatus : WebElement
        -openAll : Button
        -closeAll : Button
        -accordion : Accordion
        -shareDelighter : Delighter
        -helpDelighter : Delighter
        -trialCheckListDelighter : Delighter
        -backToSearchResults : Button

       +getCriteriaSection(): CriteriaSection
       +getStartOverLink(): Link
       +getTrialStatus(): String
       +getOpenAllButton(): Button
       +getCloseAllButton(): Button
       +getAccordion(): Accordion
       +getShareDelighter(): Delighter
       +getHelpDelighter(): Delighter
       +getTrialChecklistDelighter(): Delighter
       +getBackToSearchResults(): Button

    }
    cts.TrialDetailsPage <|-- CTSPage

    class cts.SearchNavigationResult {
        +cts.SearchNavigationResult(browser: WebDriver)

        +getAgeParameter(): string
        +getZipParameter(): string
        +getKeywordParameter(): string
        +getCancerType(): string[]
        +getResultListCount(): int
    }

}

cts.SearchNavigationResult <|-- NavigationResult

class NavigationResult {
    +NavigationResult(browser: WebDriver)

    +getPageUrl(): ParsedURL
    +getParameterValue(name: string): string
}

@enduml
